"""initial base schema

Revision ID: 0001
Revises:
Create Date: 2026-08-13

Creates the whole ``base`` schema in a single revision: the schema itself, the
two named native enum types, the shared ``base.set_updated_at()`` trigger
function, the twenty tables of SPEC-001 section 6.1 with their constraints and
timestamp columns, one ``updated_at`` trigger per table, and a ``COMMENT ON``
for every object class. ``downgrade`` is the exact mirror and leaves no residue:
it ends with an unconditional ``DROP SCHEMA base RESTRICT``. That is only safe
because ``migrations/env.py`` keeps alembic's version table out of ``base``, so
every object in the schema is owned by this revision.

Every raw-SQL string is schema qualified so that the migration never depends on
``search_path``. No secondary indexes are created: uniqueness is expressed only
through unique constraints, whose backing indexes are implicit.
"""

import textwrap
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Name of the schema owning every object created by this revision.
SCHEMA: str = "base"

# Width of every primary-key and foreign-key column: a UUIDv7 rendered as hex
# with the hyphens stripped.
ID_LENGTH: int = 32

# The twenty tables of SPEC-001 section 6.1, in foreign-key dependency order:
# parents precede children. The same order drives table creation, the trigger
# loop and (reversed) the downgrade.
TABLES: tuple[str, ...] = (
    "contact",
    "message",
    "topic",
    "document",
    "article",
    "topic_article_link",
    "article_comment",
    "subagent",
    "cv_stack_item",
    "cv_experience",
    "cv_experience_responsibility",
    "cv_stack_item_experience_link",
    "cv_education",
    "api_key",
    "admin_audit_log",
    "agent_spec",
    "agent_spec_document_link",
    "cv_skill_category",
    "cv_stack_item_category_link",
    "project",
)

# Named native enum types. ``create_type=False`` keeps ownership of the type
# lifecycle in this module: the types are created and dropped explicitly below,
# never as a side effect of a table creation.
HTTP_METHOD = postgresql.ENUM(
    "get",
    "post",
    "put",
    "patch",
    "delete",
    name="http_method",
    schema=SCHEMA,
    create_type=False,
)

DOCUMENT_TYPE = postgresql.ENUM(
    "spec",
    "acceptance",
    "other",
    name="document_type",
    schema=SCHEMA,
    create_type=False,
)


def execute_sql(statement: str) -> None:
    """execute_sql emits a raw SQL statement with consistent formatting.

    The statement is dedented and stripped of its trailing semicolon, since
    alembic terminates every statement it emits itself.

    Args:
        statement: Raw, schema-qualified SQL statement.

    Returns:
        None.
    """

    op.execute(textwrap.dedent(statement).strip().rstrip(";"))


def id_column() -> sa.Column:
    """id_column builds the primary-key column shared by every table.

    Returns:
        sa.Column: A ``VARCHAR(32)`` primary-key column holding a hyphen-free
        UUIDv7 hex string generated by the application.
    """

    return sa.Column(
        "id",
        sa.String(length=ID_LENGTH),
        nullable=False,
        comment=(
            "Primary key. UUIDv7 rendered as hex with hyphens removed, "
            "generated by the application."
        ),
    )


def fk_column(name: str, description: str, nullable: bool = False) -> sa.Column:
    """fk_column builds a foreign-key column matching the primary-key width.

    Args:
        name: Name of the column.
        description: Text used as the column comment.
        nullable: Whether the column accepts NULL values.

    Returns:
        sa.Column: A ``VARCHAR(32)`` column referencing another table's primary
        key.
    """

    return sa.Column(
        name,
        sa.String(length=ID_LENGTH),
        nullable=nullable,
        comment=description,
    )


def timestamp_columns() -> list[sa.Column]:
    """timestamp_columns builds the created_at and updated_at columns.

    Both columns are timezone aware and defaulted server side with ``now()``;
    ``updated_at`` is additionally maintained by the per-table trigger created
    in :func:`create_updated_at_trigger`.

    Returns:
        list[sa.Column]: Freshly constructed ``created_at`` and ``updated_at``
        columns, safe to attach to a single table.
    """

    return [
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
            comment=(
                "UTC timestamp of row creation. Set by the server default; "
                "never supplied by callers."
            ),
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
            comment=(
                "UTC timestamp of the last update. Maintained by the "
                "table's set_updated_at trigger."
            ),
        ),
    ]


def create_updated_at_trigger(table: str) -> None:
    """create_updated_at_trigger attaches the shared trigger to one table.

    Args:
        table: Unqualified name of the table in the ``base`` schema.

    Returns:
        None.
    """

    execute_sql(f"""
        CREATE TRIGGER {table}_set_updated_at
            BEFORE UPDATE ON {SCHEMA}.{table}
            FOR EACH ROW
            EXECUTE FUNCTION {SCHEMA}.set_updated_at();
        """)
    execute_sql(f"""
        COMMENT ON TRIGGER {table}_set_updated_at ON {SCHEMA}.{table} IS
            'Keeps {SCHEMA}.{table}.updated_at current on every UPDATE.';
        """)


def drop_updated_at_trigger(table: str) -> None:
    """drop_updated_at_trigger removes the updated_at trigger from one table.

    Args:
        table: Unqualified name of the table in the ``base`` schema.

    Returns:
        None.
    """

    execute_sql(f"DROP TRIGGER {table}_set_updated_at ON {SCHEMA}.{table};")


def create_schema() -> None:
    """create_schema creates the base schema and comments it.

    ``IF NOT EXISTS`` is retained purely so that this revision body can be
    re-run against a database where it has already been applied; no other
    component creates ``base`` beforehand. In particular alembic's own version
    table is *not* placed here - ``migrations/env.py`` configures no
    ``version_table_schema`` - so on a fresh database this statement is what
    brings the schema into existence, and everything in it is owned by this
    revision.

    Returns:
        None.
    """

    execute_sql(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA};")
    execute_sql(f"""
        COMMENT ON SCHEMA {SCHEMA} IS
            'Application schema holding every entity of the website backend.';
        """)


def drop_schema() -> None:
    """drop_schema removes the base schema once its objects are gone.

    The drop is unconditional and is the exact mirror of the schema creation in
    :func:`create_schema`. ``RESTRICT`` is deliberate: every object owned by this
    revision has been dropped explicitly by the time this runs, so the statement
    can only fail if something the revision does not own was created inside the
    schema - which must fail loudly rather than be dropped silently. Nothing
    else lives here: alembic's version table is kept outside this schema by
    ``migrations/env.py`` precisely so that this drop can be unconditional.

    Returns:
        None.
    """

    execute_sql(f"DROP SCHEMA {SCHEMA} RESTRICT;")


def create_set_updated_at_function() -> None:
    """create_set_updated_at_function creates the shared trigger function.

    One function is defined per schema and attached to every table by
    :func:`create_updated_at_trigger`.

    Returns:
        None.
    """

    execute_sql(f"""
        CREATE FUNCTION {SCHEMA}.set_updated_at()
        RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """)
    execute_sql(f"""
        COMMENT ON FUNCTION {SCHEMA}.set_updated_at() IS
            'Trigger function that stamps updated_at with the current UTC'
            ' time on every UPDATE.';
        """)


def drop_set_updated_at_function() -> None:
    """drop_set_updated_at_function removes the shared trigger function.

    Returns:
        None.
    """

    execute_sql(f"DROP FUNCTION {SCHEMA}.set_updated_at();")


def create_contact() -> None:
    """create_contact creates the base.contact table.

    Returns:
        None.
    """

    op.create_table(
        "contact",
        id_column(),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Full name of the contact.",
        ),
        sa.Column(
            "email",
            sa.String(length=320),
            nullable=False,
            comment="Email address of the contact. Unique across all contacts.",
        ),
        sa.Column(
            "organization",
            sa.String(length=255),
            nullable=True,
            comment="Organization the contact represents. NULL if not provided.",
        ),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_contact"),
        sa.UniqueConstraint("email", name="uq_contact_email"),
        schema=SCHEMA,
        comment="People who have asked to be contacted through the website.",
    )


def create_message() -> None:
    """create_message creates the base.message table.

    Returns:
        None.
    """

    op.create_table(
        "message",
        id_column(),
        fk_column("contact_id", "Contact that submitted the message."),
        sa.Column(
            "content",
            sa.Text(),
            nullable=False,
            comment="Free-form body of the message as submitted.",
        ),
        sa.Column(
            "read",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
            comment="True once an admin has marked the message as read.",
        ),
        sa.Column(
            "submitted_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="UTC timestamp at which the message was submitted.",
        ),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_message"),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            [f"{SCHEMA}.contact.id"],
            name="fk_message_contact_id",
            ondelete="CASCADE",
        ),
        schema=SCHEMA,
        comment="Messages submitted by contacts through the website.",
    )


def create_topic() -> None:
    """create_topic creates the base.topic lookup table.

    Returns:
        None.
    """

    op.create_table(
        "topic",
        id_column(),
        sa.Column(
            "name",
            sa.String(length=128),
            nullable=False,
            comment="Topic name, for example python or terraform. Unique.",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Description of the topic. NULL if not provided.",
        ),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_topic"),
        sa.UniqueConstraint("name", name="uq_topic_name"),
        schema=SCHEMA,
        comment="Lookup table of article topics.",
    )


def create_document() -> None:
    """create_document creates the base.document table.

    Returns:
        None.
    """

    op.create_table(
        "document",
        id_column(),
        sa.Column(
            "filename",
            sa.String(length=255),
            nullable=False,
            comment="Name of the stored file, including its extension.",
        ),
        sa.Column(
            "size",
            sa.Integer(),
            nullable=False,
            comment="Size of the stored content in bytes.",
        ),
        sa.Column(
            "restricted",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
            comment="True if the document is admin only, false if public.",
        ),
        sa.Column(
            "content",
            sa.LargeBinary(),
            nullable=False,
            comment="Raw document content stored in the database as bytea.",
        ),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_document"),
        schema=SCHEMA,
        comment=(
            "Generic blob store. Owners reference documents directly or "
            "through link tables; this table holds no ownership columns."
        ),
    )


def create_article() -> None:
    """create_article creates the base.article table.

    Returns:
        None.
    """

    op.create_table(
        "article",
        id_column(),
        sa.Column(
            "author",
            sa.String(length=255),
            nullable=False,
            comment="Name of the article author.",
        ),
        sa.Column(
            "display",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
            comment="Controls whether the article is shown on the website.",
        ),
        sa.Column(
            "title",
            sa.String(length=255),
            nullable=False,
            comment="Title of the article.",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=False,
            comment="Short description of the article contents.",
        ),
        fk_column(
            "document_id",
            ("Document holding the article body. NULL until content is " "attached."),
            nullable=True,
        ),
        sa.Column(
            "authored_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="UTC timestamp at which the article was authored.",
        ),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_article"),
        sa.ForeignKeyConstraint(
            ["document_id"],
            [f"{SCHEMA}.document.id"],
            name="fk_article_document_id",
            ondelete="CASCADE",
        ),
        schema=SCHEMA,
        comment=(
            "Blog article metadata. The direct document_id link is an "
            "explicit [PG-005] waiver recorded in docs/db_schema.md."
        ),
    )


def create_topic_article_link() -> None:
    """create_topic_article_link creates the base.topic_article_link table.

    Returns:
        None.
    """

    op.create_table(
        "topic_article_link",
        id_column(),
        fk_column("topic_id", "Topic assigned to the article."),
        fk_column("article_id", "Article the topic is assigned to."),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_topic_article_link"),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            [f"{SCHEMA}.topic.id"],
            name="fk_topic_article_link_topic_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            [f"{SCHEMA}.article.id"],
            name="fk_topic_article_link_article_id",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "topic_id",
            "article_id",
            name="uq_topic_article_link_topic_id_article_id",
        ),
        schema=SCHEMA,
        comment="Links topics to articles. One row per (topic, article) pair.",
    )


def create_article_comment() -> None:
    """create_article_comment creates the base.article_comment table.

    Returns:
        None.
    """

    op.create_table(
        "article_comment",
        id_column(),
        sa.Column(
            "comment",
            sa.Text(),
            nullable=False,
            comment="Free-form body of the comment.",
        ),
        sa.Column(
            "author",
            sa.String(length=255),
            nullable=True,
            comment="Name of the commenter. NULL if submitted anonymously.",
        ),
        fk_column("article_id", "Article the comment was made on."),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_article_comment"),
        sa.ForeignKeyConstraint(
            ["article_id"],
            [f"{SCHEMA}.article.id"],
            name="fk_article_comment_article_id",
            ondelete="CASCADE",
        ),
        schema=SCHEMA,
        comment="Comments made on blog articles.",
    )


def create_subagent() -> None:
    """create_subagent creates the base.subagent table.

    Returns:
        None.
    """

    op.create_table(
        "subagent",
        id_column(),
        sa.Column(
            "name",
            sa.String(length=128),
            nullable=False,
            comment="Name of the subagent as shown in the catalogue.",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=False,
            comment="Description of what the subagent does.",
        ),
        sa.Column(
            "inputs",
            postgresql.JSONB(),
            nullable=True,
            comment="Input schema of the subagent. NULL if unspecified.",
        ),
        sa.Column(
            "outputs",
            postgresql.JSONB(),
            nullable=True,
            comment="Output schema of the subagent. NULL if unspecified.",
        ),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_subagent"),
        schema=SCHEMA,
        comment=(
            "Agent catalogue entries. The JSONB columns are an explicit "
            "[PG-014] waiver recorded in docs/db_schema.md."
        ),
    )


def create_cv_stack_item() -> None:
    """create_cv_stack_item creates the base.cv_stack_item lookup table.

    Returns:
        None.
    """

    op.create_table(
        "cv_stack_item",
        id_column(),
        sa.Column(
            "name",
            sa.String(length=128),
            nullable=False,
            comment="Name of the technology, for example golang. Unique.",
        ),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_cv_stack_item"),
        sa.UniqueConstraint("name", name="uq_cv_stack_item_name"),
        schema=SCHEMA,
        comment="Lookup table of technologies shared across CV entries.",
    )


def create_cv_experience() -> None:
    """create_cv_experience creates the base.cv_experience table.

    Returns:
        None.
    """

    op.create_table(
        "cv_experience",
        id_column(),
        sa.Column(
            "organization",
            sa.String(length=255),
            nullable=False,
            comment="Organization the experience was gained at.",
        ),
        sa.Column(
            "job_title",
            sa.String(length=255),
            nullable=False,
            comment="Job title held during the experience.",
        ),
        sa.Column(
            "start_date",
            sa.Date(),
            nullable=False,
            comment="Date the role started.",
        ),
        sa.Column(
            "end_date",
            sa.Date(),
            nullable=True,
            comment="Date the role ended. NULL while the role is current.",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=False,
            comment="Free-form description of the role.",
        ),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_cv_experience"),
        schema=SCHEMA,
        comment="Work experience entries of the CV.",
    )


def create_cv_experience_responsibility() -> None:
    """create_cv_experience_responsibility creates the responsibility table.

    Returns:
        None.
    """

    op.create_table(
        "cv_experience_responsibility",
        id_column(),
        fk_column("experience_id", "Experience the responsibility belongs to."),
        sa.Column(
            "description",
            sa.Text(),
            nullable=False,
            comment="Free-form description of the responsibility.",
        ),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_cv_experience_responsibility"),
        sa.ForeignKeyConstraint(
            ["experience_id"],
            [f"{SCHEMA}.cv_experience.id"],
            name="fk_cv_experience_responsibility_experience_id",
            ondelete="CASCADE",
        ),
        schema=SCHEMA,
        comment="Responsibilities held during a CV work experience entry.",
    )


def create_cv_stack_item_experience_link() -> None:
    """create_cv_stack_item_experience_link creates the stack/experience link.

    Returns:
        None.
    """

    op.create_table(
        "cv_stack_item_experience_link",
        id_column(),
        fk_column("stack_item_id", "Stack item used during the experience."),
        fk_column("experience_id", "Experience the stack item was used in."),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_cv_stack_item_experience_link"),
        sa.ForeignKeyConstraint(
            ["stack_item_id"],
            [f"{SCHEMA}.cv_stack_item.id"],
            name="fk_cv_stack_item_experience_link_stack_item_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["experience_id"],
            [f"{SCHEMA}.cv_experience.id"],
            name="fk_cv_stack_item_experience_link_experience_id",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "stack_item_id",
            "experience_id",
            name="uq_cv_stack_item_experience_link_stack_experience",
        ),
        schema=SCHEMA,
        comment=(
            "Links stack items to CV experiences. One row per "
            "(stack item, experience) pair."
        ),
    )


def create_cv_education() -> None:
    """create_cv_education creates the base.cv_education table.

    Returns:
        None.
    """

    op.create_table(
        "cv_education",
        id_column(),
        sa.Column(
            "institution",
            sa.String(length=255),
            nullable=False,
            comment="Institution the certificate was obtained at.",
        ),
        sa.Column(
            "certificate",
            sa.String(length=128),
            nullable=False,
            comment="Type of certificate, for example bsc, masters or phd.",
        ),
        sa.Column(
            "start_date",
            sa.Date(),
            nullable=False,
            comment="Date the course started.",
        ),
        sa.Column(
            "end_date",
            sa.Date(),
            nullable=True,
            comment="Date the course ended. NULL while ongoing.",
        ),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_cv_education"),
        schema=SCHEMA,
        comment="Education entries of the CV.",
    )


def create_api_key() -> None:
    """create_api_key creates the base.api_key table.

    Returns:
        None.
    """

    op.create_table(
        "api_key",
        id_column(),
        sa.Column(
            "api_key",
            sa.String(length=64),
            nullable=False,
            comment=(
                "SHA-256 hash of the API key as 64 hex characters. Plaintext "
                "keys are never stored. Unique across all keys."
            ),
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=False,
            comment="Description of what the key is used for.",
        ),
        sa.Column(
            "issued_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="UTC timestamp at which the key was issued.",
        ),
        sa.Column(
            "expires_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="UTC expiry timestamp. NULL if the key never expires.",
        ),
        sa.Column(
            "issued_for",
            sa.String(length=255),
            nullable=False,
            comment="Name of the user the key was issued to.",
        ),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_api_key"),
        sa.UniqueConstraint("api_key", name="uq_api_key_api_key"),
        schema=SCHEMA,
        comment="Hashed API keys used by admins to authenticate.",
    )


def create_admin_audit_log() -> None:
    """create_admin_audit_log creates the base.admin_audit_log table.

    Returns:
        None.
    """

    op.create_table(
        "admin_audit_log",
        id_column(),
        fk_column(
            "api_key_id",
            (
                "API key the request authenticated with. NULL when the request "
                "presented no valid key. This is an explicit, user-approved "
                "deviation from SPEC-001 6.1.9, which defaults the column to "
                "non-nullable: the acceptance suite's api.feature scenario "
                "'An unauthenticated admin request is recorded in the audit "
                "log' and every invalid-API-key example require an audit row "
                "for a request without a valid key. The foreign key and its "
                "ON DELETE RESTRICT action are unchanged."
            ),
            nullable=True,
        ),
        sa.Column(
            "endpoint",
            sa.String(length=512),
            nullable=False,
            comment="Path of the admin endpoint that was called.",
        ),
        sa.Column(
            "method",
            HTTP_METHOD,
            nullable=False,
            comment="HTTP method of the request.",
        ),
        sa.Column(
            "status_code",
            sa.Integer(),
            nullable=False,
            comment="HTTP status code returned by the endpoint.",
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(),
            nullable=True,
            comment="Request payload. NULL if the request had no body.",
        ),
        sa.Column(
            "response",
            postgresql.JSONB(),
            nullable=True,
            comment="Response payload. NULL if the response had no body.",
        ),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_admin_audit_log"),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            [f"{SCHEMA}.api_key.id"],
            name="fk_admin_audit_log_api_key_id",
            ondelete="RESTRICT",
        ),
        schema=SCHEMA,
        comment=(
            "Audit log of authenticated admin requests. The JSONB columns are "
            "an explicit [PG-014] waiver recorded in docs/db_schema.md."
        ),
    )


def create_agent_spec() -> None:
    """create_agent_spec creates the base.agent_spec table.

    Returns:
        None.
    """

    op.create_table(
        "agent_spec",
        id_column(),
        sa.Column(
            "display_name",
            sa.String(length=255),
            nullable=False,
            comment="Name of the spec as shown on the website.",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=False,
            comment="Description of what the spec provides.",
        ),
        sa.Column(
            "display",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
            comment="Controls whether the spec is shown on the website.",
        ),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_agent_spec"),
        schema=SCHEMA,
        comment="Metadata for the specs used by agents to generate the site.",
    )


def create_agent_spec_document_link() -> None:
    """create_agent_spec_document_link creates the spec/document link table.

    Returns:
        None.
    """

    op.create_table(
        "agent_spec_document_link",
        id_column(),
        fk_column("spec_id", "Spec the document belongs to."),
        fk_column("document_id", "Document linked to the spec."),
        sa.Column(
            "document_type",
            DOCUMENT_TYPE,
            nullable=False,
            comment="Role the document plays for the spec.",
        ),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_agent_spec_document_link"),
        sa.ForeignKeyConstraint(
            ["spec_id"],
            [f"{SCHEMA}.agent_spec.id"],
            name="fk_agent_spec_document_link_spec_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            [f"{SCHEMA}.document.id"],
            name="fk_agent_spec_document_link_document_id",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "spec_id",
            "document_id",
            name="uq_agent_spec_document_link_spec_id_document_id",
        ),
        schema=SCHEMA,
        comment="Links documents to specs. One row per (spec, document) pair.",
    )


def create_cv_skill_category() -> None:
    """create_cv_skill_category creates the base.cv_skill_category table.

    Returns:
        None.
    """

    op.create_table(
        "cv_skill_category",
        id_column(),
        sa.Column(
            "category",
            sa.String(length=128),
            nullable=False,
            comment=("Skill grouping, for example Programming Languages. Unique."),
        ),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_cv_skill_category"),
        sa.UniqueConstraint("category", name="uq_cv_skill_category_category"),
        schema=SCHEMA,
        comment="Lookup table of categories used to group CV skills.",
    )


def create_cv_stack_item_category_link() -> None:
    """create_cv_stack_item_category_link creates the category link table.

    Returns:
        None.
    """

    op.create_table(
        "cv_stack_item_category_link",
        id_column(),
        fk_column("category_id", "Skill category the stack item belongs to."),
        fk_column("stack_item_id", "Stack item assigned to the category."),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_cv_stack_item_category_link"),
        sa.ForeignKeyConstraint(
            ["category_id"],
            [f"{SCHEMA}.cv_skill_category.id"],
            name="fk_cv_stack_item_category_link_category_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stack_item_id"],
            [f"{SCHEMA}.cv_stack_item.id"],
            name="fk_cv_stack_item_category_link_stack_item_id",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "category_id",
            "stack_item_id",
            name="uq_cv_stack_item_category_link_category_stack_item",
        ),
        schema=SCHEMA,
        comment=(
            "Links stack items to skill categories. One row per "
            "(category, stack item) pair."
        ),
    )


def create_project() -> None:
    """create_project creates the base.project table.

    Returns:
        None.
    """

    op.create_table(
        "project",
        id_column(),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Name of the project.",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=False,
            comment="Description of what the project does.",
        ),
        sa.Column(
            "primary_link",
            sa.String(length=512),
            nullable=False,
            comment="Primary URL of the project.",
        ),
        sa.Column(
            "github_link",
            sa.String(length=512),
            nullable=True,
            comment="GitHub URL of the project. NULL if not public.",
        ),
        sa.Column(
            "display",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
            comment="Controls whether the project is shown on the website.",
        ),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_project"),
        schema=SCHEMA,
        comment="Personal and company projects shown on the website.",
    )


# Table builders keyed by table name. The iteration order of TABLES drives both
# the creation order here and, reversed, the drop order in downgrade.
TABLE_BUILDERS = {
    "contact": create_contact,
    "message": create_message,
    "topic": create_topic,
    "document": create_document,
    "article": create_article,
    "topic_article_link": create_topic_article_link,
    "article_comment": create_article_comment,
    "subagent": create_subagent,
    "cv_stack_item": create_cv_stack_item,
    "cv_experience": create_cv_experience,
    "cv_experience_responsibility": create_cv_experience_responsibility,
    "cv_stack_item_experience_link": create_cv_stack_item_experience_link,
    "cv_education": create_cv_education,
    "api_key": create_api_key,
    "admin_audit_log": create_admin_audit_log,
    "agent_spec": create_agent_spec,
    "agent_spec_document_link": create_agent_spec_document_link,
    "cv_skill_category": create_cv_skill_category,
    "cv_stack_item_category_link": create_cv_stack_item_category_link,
    "project": create_project,
}


def upgrade() -> None:
    """upgrade applies the schema changes of this revision.

    Objects are emitted in strict dependency order: the schema, both enum
    types and the trigger function first, then the twenty tables parents
    before children, then one updated_at trigger per table. Each enum type is
    commented immediately after it is created; the comment lives and dies with
    the type, so :func:`downgrade` has no counterpart to emit.

    Returns:
        None.
    """

    create_schema()

    bind = op.get_bind()
    HTTP_METHOD.create(bind, checkfirst=False)
    execute_sql(f"""
        COMMENT ON TYPE {SCHEMA}.http_method IS
            'HTTP method of the request recorded on an admin audit-log entry.';
        """)

    DOCUMENT_TYPE.create(bind, checkfirst=False)
    execute_sql(f"""
        COMMENT ON TYPE {SCHEMA}.document_type IS
            'Role a linked document plays for an agent spec.';
        """)

    create_set_updated_at_function()

    for table in TABLES:
        TABLE_BUILDERS[table]()

    for table in TABLES:
        create_updated_at_trigger(table)


def downgrade() -> None:
    """downgrade reverts the schema changes of this revision.

    The mirror of :func:`upgrade`: triggers, then tables in reverse dependency
    order, then the trigger function, both enum types and finally the schema
    itself.

    Returns:
        None.
    """

    for table in reversed(TABLES):
        drop_updated_at_trigger(table)

    for table in reversed(TABLES):
        op.drop_table(table, schema=SCHEMA)

    drop_set_updated_at_function()

    bind = op.get_bind()
    DOCUMENT_TYPE.drop(bind, checkfirst=False)
    HTTP_METHOD.drop(bind, checkfirst=False)

    drop_schema()
