apiVersion: batch/v1
kind: Job
metadata:
  name: load-seed-data
  namespace: personal-website
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: load-seed-data
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: aws-ecr-credentials
      containers:
        - name: load-seed-data
          image: 450876623734.dkr.ecr.us-east-1.amazonaws.com/personal-website/load-seed-data
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: "postgres-dev-rw.shared-infra"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: personal_website
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-creds-dev
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds-dev
                  key: password
